/**
 * Write a review to disk: one source file per diagram plus a REVIEW.md index.
 * Mermaid diagrams are embedded inline so they render directly on GitHub; drawio
 * files link out (open in the ArchAI web app or the drawio desktop/VS Code app).
 */

import { promises as fs } from "node:fs";
import path from "node:path";

import type { ReviewResult, StackInfo } from "./types.js";

function stackTable(s: StackInfo): string {
  const row = (k: string, v: string) => `| ${k} | ${v || "—"} |`;
  return [
    "| Aspect | Detected |",
    "| --- | --- |",
    row("Languages", s.languages.join(", ")),
    row("Frameworks", s.frameworks.join(", ")),
    row("Infra-as-code", s.iac.join(", ")),
    row("Datastores", s.datastores.join(", ")),
    row("Docker", s.hasDocker ? "yes" : "no"),
    row("CI", s.hasCi ? "yes" : "no"),
  ].join("\n");
}

function buildReadme(result: ReviewResult): string {
  const { digest, plan, diagrams } = result;
  const repoName = digest.root.split("/").pop() || "repository";
  const lines: string[] = [];

  lines.push(`# Architecture Review — ${repoName}`);
  lines.push("");
  lines.push(`> Generated by [ArchAI Reviewer](https://github.com/ravi-labs/archai). Diagrams are a first draft from static analysis + an LLM — verify against reality.`);
  lines.push("");
  if (plan.summary) { lines.push(plan.summary); lines.push(""); }

  lines.push("## Detected stack");
  lines.push("");
  lines.push(stackTable(digest.stack));
  lines.push("");

  lines.push("## Diagrams");
  lines.push("");
  diagrams.forEach((d, i) => {
    lines.push(`### ${i + 1}. ${d.title}`);
    lines.push("");
    lines.push(`*${d.kind}*${d.rationale ? ` — ${d.rationale}` : ""}`);
    lines.push("");
    if (d.error) {
      lines.push(`> ⚠️ Generation failed: ${d.error}`);
      lines.push("");
      return;
    }
    if (d.format === "mermaid") {
      lines.push("```mermaid");
      lines.push(d.source);
      lines.push("```");
      lines.push("");
      lines.push(`[source: \`${d.fileName}\`](./${d.fileName})`);
    } else {
      lines.push(`📐 drawio diagram: [\`${d.fileName}\`](./${d.fileName})`);
      lines.push("");
      lines.push(`Open it in the [ArchAI web app](https://ravi-labs.github.io/archai/) (Load existing diagram), the drawio desktop app, or the drawio VS Code extension.`);
    }
    lines.push("");
  });

  return lines.join("\n");
}

export interface WriteResult {
  outDir: string;
  written: string[];
  reviewPath: string;
  failed: number;
}

export async function writeReview(outDir: string, result: ReviewResult): Promise<WriteResult> {
  await fs.mkdir(outDir, { recursive: true });
  const written: string[] = [];
  let failed = 0;

  for (const d of result.diagrams) {
    if (d.error || !d.source) { failed++; continue; }
    const p = path.join(outDir, d.fileName);
    await fs.writeFile(p, d.source, "utf8");
    written.push(d.fileName);
  }

  const reviewPath = path.join(outDir, "REVIEW.md");
  await fs.writeFile(reviewPath, buildReadme(result), "utf8");

  return { outDir, written, reviewPath, failed };
}
